### ISSUE TITLE
Reference papers

### ISSUE THREAD

**Issue by HappyDay-design** [DDeChoU/Selfless-Traffic-Routing-Testbed#28]
Hello

Thank you for sharing your models. It is helpful for me to apply traffic navigation.
Could you please upload your papers related to models
Thanks

**Comment by guangli-dai** [comment]
[RL_Traffic_Camera_Ready.pdf](https://github.com/guangli-dai/Selfless-Traffic-Routing-Testbed/files/10974586/RL_Traffic_Camera_Ready.pdf) Here is the camera-ready version of the paper.
