### ISSUE TITLE
How can I try to train my traffic？

### ISSUE THREAD

**Issue by lostking91** [DDeChoU/Selfless-Traffic-Routing-Testbed#5]
hello, I am a newbie in traffic routing RL development . I learn your code. But I want to train my own traffic, can you tell me how can I train it. Or can you share your experience  and beginner's guide in traffic routing RL development? Example best. Thank you!

**Comment by DDeChoU** [comment]
Hi,
This is a sample workflow in the training of a Q-learning agent:
![image](https://user-images.githubusercontent.com/13465172/87689873-583d2480-c74e-11ea-88f4-44f59a790be0.png)
Take a look at QLearningController.py. Codes inside should help when you build the training part.
